Update documentation on how to use this repository
Remi-Gau/reproschema_app_template pull request #3
Opened 2020-11-12 16:45 UTC by Remi-Gau

2020-11-12 17:15 UTC, Remi-Gau reviewed
things to change

2020-11-12 17:15 UTC, Remi-Gau commented on README.md
> +      something like the snippet of code below:
```suggestion
- [ ] Make sure to modify `.github/workflows/build_deploy.yml`, so that the
      reproschema python package will run on the right protocol_schema. Look for
      something like the snippet of code below:
```

2020-11-12 17:15 UTC, Remi-Gau commented on README.md
> +- [ ] Clone the newly created repository.
Add a link to documentation `git clone`

2020-11-12 17:22 UTC, jasminetan6032 requested changes

2020-11-12 17:22 UTC, jasminetan6032 commented on README.md
> +      [template to create a new repository on your account](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template).
```suggestion
- [ ] Click 'Use this
      [template' to create a new repository on your account](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template).
```

2020-11-14 06:04 UTC, Remi-Gau commented on README.md
> +      [template' to create a new repository on your account](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template).
```suggestion
- [ ] Click `Use this template` to [create a new repository on your account](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template).
```

2020-12-12 11:56 UTC, merged